export const ADD_STUDENT_REQUEST = "ADD_STUDENT_REQUEST";
export const ADD_STUDENT_SUCCESS = "ADD_STUDENT_SUCCESS";
export const ADD_STUDENT_RESET = "ADD_STUDENT_RESET";
export const ADD_STUDENT_FAIL = "ADD_STUDENT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";